export const dataImages = {
  landings: [
    {
      id: 1,
      name: 'Dvc',
      preview: '/images/landings/3DVC/dvc_0.png',
      images: ['/images/landings/3DVC/dvc_1.png'],
    },
    {
      id: 2,
      name: 'Cool Job',
      preview: '/images/landings/сooljob_home/Cooljob_home_0.png',
      images: ['/images/landings/сooljob_home/Cooljob_home_1.png'],
    },
    {
      id: 3,
      name: 'Alcan',
      preview: '/images/landings/Alcan/Alcan_0.png',
      images: [
        '/images/landings/Alcan/Alcan_1_1.png',
        '/images/landings/Alcan/Alcan_1_2.png',
        '/images/landings/Alcan/Alcan_1_3.png',
        '/images/landings/Alcan/Alcan_1.png',
      ],
    },
    {
      id: 4,
      name: 'Dances',
      preview: '/images/landings/dances/dens_0.png',
      images: ['/images/landings/dances/dens_1.png'],
    },
    {
      id: 6,
      name: 'Vershina',
      preview: '/images/landings/vershina/vershina_0.png',
      images: ['/images/landings/vershina/vershina_1.png'],
    },
    {
      id: 61,
      name: 'Porolosh',
      preview: '/cla_images/Poroloshka/Poroloshka_0.jpg',
      images: [
        './cla_images/Poroloshka/Poroloshka_1.jpg',
        './cla_images/Poroloshka/Poroloshka_1_1.jpg',
      ],
    },
  ],
  multiPage: [
    {
      id: 7,
      name: 'Woodhouse',
      preview: '/images/multypage/woodhouse/woodhouse_0.png',
      images: [
        '/images/multypage/woodhouse/woodhouse_1.png',
        '/images/multypage/woodhouse/woodhouse_2.png',
        '/images/multypage/woodhouse/woodhouse_3.png',
        '/images/multypage/woodhouse/woodhouse_5.png',
        '/images/multypage/woodhouse/woodhouse_6.png',
        '/images/multypage/woodhouse/woodhouse_7.png',
        '/images/multypage/woodhouse/woodhouse_8.png',
        '/images/multypage/woodhouse/woodhouse_9.png',
        '/images/multypage/woodhouse/woodhouse_10.png',
      ],
    },
    {
      id: 8,
      name: 'Burmash',
      preview: '/cla_images/burmash_main/burmash_0.png',
      images: [
        '/cla_images/burmash_main/burmash_1.png',
        '/cla_images/burmash_main/burmash_1_1.png',
        '/cla_images/burmash_main/burmash_1_2.png',
        '/cla_images/burmash_main/burmash_1_3.png',
        '/cla_images/burmash_main/burmash_1_4.png',
        '/cla_images/burmash_main/burmash_1_5.png',
        '/cla_images/burmash_main/burmash_2.png',
        '/cla_images/burmash_main/burmash_3.png',
        '/cla_images/burmash_main/burmash_4.png',
        '/cla_images/burmash_main/burmash_5.png',
        '/cla_images/burmash_main/burmash_6.png',
      ],
    },
    {
      id: 9,
      name: 'Sota',
      preview: '/cla_images/Sota/Sota_0.png',
      images: [
        '/cla_images/Sota/sota_1.png',
        '/cla_images/Sota/sota_1_1.png',
        '/cla_images/Sota/sota_2.png',
        '/cla_images/Sota/sota_3.png',
        '/cla_images/Sota/sota_1_3.png',
        '/cla_images/Sota/sota_4.png',
        '/cla_images/Sota/sota_1_4.png',
        '/cla_images/Sota/Sota_5.png',
        '/cla_images/Sota/sota_1_5.png',
        '/cla_images/Sota/sota_6.png',
        '/cla_images/Sota/sota_1_6.png',
        '/cla_images/Sota/sota_7.png',
        '/cla_images/Sota/sota_8.png',
        '/cla_images/Sota/sota_1_8.png',
        '/cla_images/Sota/sota_9.png',
        '/cla_images/Sota/sota_1_9.png',
        '/cla_images/Sota/sota_10.png',
        '/cla_images/Sota/sota_1_10.png',
        '/cla_images/Sota/sota_12.png',
        '/cla_images/Sota/sota_1_12.png',
      ],
    },
    {
      id: 10,
      name: 'SPK Group',
      preview: '/cla_images/SPB_site/СПБ_0.png',
      images: [
        '/cla_images/SPB_site/СПБ_1.png',
        '/cla_images/SPB_site/СПБ_1_1.png',
        '/cla_images/SPB_site/СПБ_2.png',
        '/cla_images/SPB_site/СПБ_1_2.png',
        '/cla_images/SPB_site/СПБ_3.png',
        '/cla_images/SPB_site/СПБ_1_3.png',
        '/cla_images/SPB_site/СПБ_4.png',
        '/cla_images/SPB_site/СПБ_1_4.png',
        '/cla_images/SPB_site/СПБ_5.png',
        '/cla_images/SPB_site/СПБ_1_5.png',
        '/cla_images/SPB_site/СПБ_6.png',
        '/cla_images/SPB_site/СПБ_1_6.png',
        '/cla_images/SPB_site/СПБ_7.png',
        '/cla_images/SPB_site/СПБ_1_7.png',
      ],
    },
    {
      id: 11,
      name: 'Suventr Avenew',
      preview: '/cla_images/Suvenir/Suvenir_0.png',
      images: [
        '/cla_images/Suvenir/suvenir_1.png',
        '/cla_images/Suvenir/suvenir_1_1.png',
        '/cla_images/Suvenir/suvenir_2.png',
        '/cla_images/Suvenir/suvenir_1_2.png',
        '/cla_images/Suvenir/suvenir_3.png',
        '/cla_images/Suvenir/suvenir_1_3.png',
        '/cla_images/Suvenir/suvenir_4.png',
        '/cla_images/Suvenir/suvenir_1_4.png',
        '/cla_images/Suvenir/suvenir_5.png',
        '/cla_images/Suvenir/suvenir_1_5.png',
        '/cla_images/Suvenir/suvenir_6.png',
        '/cla_images/Suvenir/suvenir_7.png',
        '/cla_images/Suvenir/suvenir_8.png',
      ],
    },
  ],
  apps: [
    {
      id: 15,
      name: 'Bank App',
      preview: '/images/applications/modil_0.png',
      images: [
        '/images/applications/modil_0_1.png',
        '/images/applications/modil_0.png',
        '/images/applications/modil_1.png',
        '/images/applications/modil_2.png',
        '/images/applications/modil_3.png',
        '/images/applications/modil_4.png',
        '/images/applications/modil_5.png',
      ],
    },
  ],
  bunners: [
    {
      id: 21,
      name: 'Edu',
      preview: '/images/banner/Edu/Edu_0.png',
      images: ['/images/banner/Edu/Edu_0.png'],
    },
  ],
};
