export const dataImages = {
  landings: [
    {
      id: 1,
      name: 'Dvc',
      link: 'dvc',
      description:
        'Современный, интуитивный интерфейс, необычная визуализации, удобная навигация, информация о спикерах и расписании.',
      preview: 'https://storage.yandexcloud.net/rt-pepper/cla-porfolio/landings/dvc/dvc_0.png',
      images: ['https://storage.yandexcloud.net/rt-pepper/cla-porfolio/landings/dvc/dvc_1.png'],
    },
    {
      id: 2,
      name: 'Cool Job',
      link: 'cooljob',
      description:
        'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Cum quibusdam numquam recusandae corrupti enim veritatis, vel ab adipisci rerum facere.',
      preview:
        'https://storage.yandexcloud.net/rt-pepper/cla-porfolio/landings/cooljob/Cooljob_home_0.png',
      images: [
        'https://storage.yandexcloud.net/rt-pepper/cla-porfolio/landings/cooljob/Cooljob_home_1.png',
      ],
    },
    {
      id: 3,
      name: 'Alcan',
      link: 'alcan',
      description:
        'Создание адаптивного макета сайта с использованием медиа-запросов CSS, гибкой сетки и масштабируемых изображений для оптимального отображения на разных устройствах.',
      preview: 'https://storage.yandexcloud.net/rt-pepper/cla-porfolio/landings/alcan/Alcan_0.png',
      images: [
        'https://storage.yandexcloud.net/rt-pepper/cla-porfolio/landings/alcan/Alcan_1.png',
        'https://storage.yandexcloud.net/rt-pepper/cla-porfolio/landings/alcan/Alcan_1_1.png',
        'https://storage.yandexcloud.net/rt-pepper/cla-porfolio/landings/alcan/Alcan_1_2.png',
        'https://storage.yandexcloud.net/rt-pepper/cla-porfolio/landings/alcan/Alcan_1_3.png',
      ],
    },
    {
      id: 4,
      name: 'Dances',
      link: 'dances',
      description:
        'Сайт по танцам предлагает уроки, видеоуроки, статьи и советы для танцоров всех уровней. Удобный интерфейс и разнообразие стилей!',
      preview: 'https://storage.yandexcloud.net/rt-pepper/cla-porfolio/landings/dances/dens_0.png',
      images: ['https://storage.yandexcloud.net/rt-pepper/cla-porfolio/landings/dances/dens_1.png'],
    },
    {
      id: 6,
      name: 'Vershina',
      link: 'vershina',
      description:
        'Природный парк Ергаки — живописное место в Сибири с уникальными ландшафтами, горами, озерами и разнообразной флорой и фауной.',
      preview: 'https://storage.yandexcloud.net/rt-pepper/cla-porfolio/landings/vershina/vershina_0.png',
      images: ['https://storage.yandexcloud.net/rt-pepper/cla-porfolio/landings/vershina/vershina_1.png'],
    },
    {
      id: 61,
      name: 'Porolosh',
      link: 'porolosh',
      description:
        'Сайт предлагает широкий ассортимент рыбных снастей: удочки, катушки, приманки и аксессуары. Удобная навигация и полезные советы для рыбаков, фото и видео улова.',
      preview: 'https://storage.yandexcloud.net/rt-pepper/cla-porfolio/poroloshka/Poroloshka_0.jpg',
      images: [
        'https://storage.yandexcloud.net/rt-pepper/cla-porfolio/poroloshka/Poroloshka_1.jpg',
        'https://storage.yandexcloud.net/rt-pepper/cla-porfolio/poroloshka/Poroloshka_1_1.jpg',
      ],
    },
  ],
  multiPage: [
    {
      id: 7,
      name: 'Woodhouse',
      link: 'woodhouse',
      description:
        'Сайт предлагает уникальные интерьеры из дерева, сочетая экологичность и стиль. Вдохновение для уютного и современного дизайна вашего дома.',
      preview: 'https://storage.yandexcloud.net/rt-pepper/cla-porfolio/multipage/woodhouse/woodhouse_0.png',
      images: [
        'https://storage.yandexcloud.net/rt-pepper/cla-porfolio/multipage/woodhouse/woodhouse_1.png',
        'https://storage.yandexcloud.net/rt-pepper/cla-porfolio/multipage/woodhouse/woodhouse_2.png',
        'https://storage.yandexcloud.net/rt-pepper/cla-porfolio/multipage/woodhouse/woodhouse_3.png',
        'https://storage.yandexcloud.net/rt-pepper/cla-porfolio/multipage/woodhouse/woodhouse_5.png',
        'https://storage.yandexcloud.net/rt-pepper/cla-porfolio/multipage/woodhouse/woodhouse_6.png',
        'https://storage.yandexcloud.net/rt-pepper/cla-porfolio/multipage/woodhouse/woodhouse_7.png',
        'https://storage.yandexcloud.net/rt-pepper/cla-porfolio/multipage/woodhouse/woodhouse_8.png',
        'https://storage.yandexcloud.net/rt-pepper/cla-porfolio/multipage/woodhouse/woodhouse_9.png',
        'https://storage.yandexcloud.net/rt-pepper/cla-porfolio/multipage/woodhouse/woodhouse_10.png',
      ],
    },
    {
      id: 8,
      name: 'Burmash',
      link: 'burmash',
      description:
        'Сайт предлагает широкий ассортимент шнеков, включая характеристики, применение и технические детали для различных отраслей.',
      preview: 'https://storage.yandexcloud.net/rt-pepper/cla-porfolio/burmash/burmash_0.png',
      images: [
        'https://storage.yandexcloud.net/rt-pepper/cla-porfolio/burmash/burmash_1.png',
        'https://storage.yandexcloud.net/rt-pepper/cla-porfolio/burmash/burmash_1_1.png',
        'https://storage.yandexcloud.net/rt-pepper/cla-porfolio/burmash/burmash_2.png',
        'https://storage.yandexcloud.net/rt-pepper/cla-porfolio/burmash/burmash_1_2.png',
        'https://storage.yandexcloud.net/rt-pepper/cla-porfolio/burmash/burmash_3.png',
        'https://storage.yandexcloud.net/rt-pepper/cla-porfolio/burmash/burmash_1_3.png',
        'https://storage.yandexcloud.net/rt-pepper/cla-porfolio/burmash/burmash_4.png',
        'https://storage.yandexcloud.net/rt-pepper/cla-porfolio/burmash/burmash_1_4.png',
        'https://storage.yandexcloud.net/rt-pepper/cla-porfolio/burmash/burmash_5.png',
        'https://storage.yandexcloud.net/rt-pepper/cla-porfolio/burmash/burmash_1_5.png',
        'https://storage.yandexcloud.net/rt-pepper/cla-porfolio/burmash/burmash_6.png',
      ],
    },
    {
      id: 9,
      name: 'Sota',
      link: 'sota',
      description:
        'Сайт предлагает широкий выбор теплиц и садовых домов, предоставляет полезные советы по их строительству, выбору материалов и уходу, а также вдохновляющие идеи для вашего сада.',
      preview: 'https://storage.yandexcloud.net/rt-pepper/cla-porfolio/sota/sota_0.png',
      images: [
        'https://storage.yandexcloud.net/rt-pepper/cla-porfolio/sota/sota_1.png',
        'https://storage.yandexcloud.net/rt-pepper/cla-porfolio/sota/sota_1_1.png',
        'https://storage.yandexcloud.net/rt-pepper/cla-porfolio/sota/sota_2.png',
        'https://storage.yandexcloud.net/rt-pepper/cla-porfolio/sota/sota_3.png',
        'https://storage.yandexcloud.net/rt-pepper/cla-porfolio/sota/sota_1_3.png',
        'https://storage.yandexcloud.net/rt-pepper/cla-porfolio/sota/sota_4.png',
        'https://storage.yandexcloud.net/rt-pepper/cla-porfolio/sota/sota_1_4.png',
        'https://storage.yandexcloud.net/rt-pepper/cla-porfolio/sota/sota_5.png',
        'https://storage.yandexcloud.net/rt-pepper/cla-porfolio/sota/sota_1_5.png',
        'https://storage.yandexcloud.net/rt-pepper/cla-porfolio/sota/sota_6.png',
        'https://storage.yandexcloud.net/rt-pepper/cla-porfolio/sota/sota_1_6.png',
        'https://storage.yandexcloud.net/rt-pepper/cla-porfolio/sota/sota_7.png',
        'https://storage.yandexcloud.net/rt-pepper/cla-porfolio/sota/sota_8.png',
        'https://storage.yandexcloud.net/rt-pepper/cla-porfolio/sota/sota_1_8.png',
        'https://storage.yandexcloud.net/rt-pepper/cla-porfolio/sota/sota_9.png',
        'https://storage.yandexcloud.net/rt-pepper/cla-porfolio/sota/sota_1_9.png',
        'https://storage.yandexcloud.net/rt-pepper/cla-porfolio/sota/sota_10.png',
        'https://storage.yandexcloud.net/rt-pepper/cla-porfolio/sota/sota_1_10.png',
        'https://storage.yandexcloud.net/rt-pepper/cla-porfolio/sota/sota_12.png',
        'https://storage.yandexcloud.net/rt-pepper/cla-porfolio/sota/sota_1_12.png',
      ],
    },
    {
      id: 10,
      name: 'SPK Group',
      link: 'spkgroup',
      description: 'Многостраничный сайт завода по производству дробеструйных камер.',
      preview: 'https://storage.yandexcloud.net/rt-pepper/cla-porfolio/spb/spb_0.png',
      images: [
        'https://storage.yandexcloud.net/rt-pepper/cla-porfolio/spb/spb_1.png',
        'https://storage.yandexcloud.net/rt-pepper/cla-porfolio/spb/spb_1_1.png',
        'https://storage.yandexcloud.net/rt-pepper/cla-porfolio/spb/spb_2.png',
        'https://storage.yandexcloud.net/rt-pepper/cla-porfolio/spb/spb_1_2.png',
        'https://storage.yandexcloud.net/rt-pepper/cla-porfolio/spb/spb_3.png',
        'https://storage.yandexcloud.net/rt-pepper/cla-porfolio/spb/spb_1_3.png',
        'https://storage.yandexcloud.net/rt-pepper/cla-porfolio/spb/spb_4.png',
        'https://storage.yandexcloud.net/rt-pepper/cla-porfolio/spb/spb_1_4.png',
        'https://storage.yandexcloud.net/rt-pepper/cla-porfolio/spb/spb_5.png',
        'https://storage.yandexcloud.net/rt-pepper/cla-porfolio/spb/spb_1_5.png',
        'https://storage.yandexcloud.net/rt-pepper/cla-porfolio/spb/spb_6.png',
        'https://storage.yandexcloud.net/rt-pepper/cla-porfolio/spb/spb_1_6.png',
        'https://storage.yandexcloud.net/rt-pepper/cla-porfolio/spb/spb_7.png',
        'https://storage.yandexcloud.net/rt-pepper/cla-porfolio/spb/spb_1_7.png',
      ],
    },
    {
      id: 11,
      name: 'Suventr Avenew',
      link: 'suvenir',
      description:
        'Интуитивно понятный интерфейс, широкий ассортимент товаров, удобная навигация, безопасные способы оплаты и быстрая доставка.',
      preview: 'https://storage.yandexcloud.net/rt-pepper/cla-porfolio/suvenir/Suvenir_0.png',
      images: [
        'https://storage.yandexcloud.net/rt-pepper/cla-porfolio/suvenir/suvenir_1.png',
        'https://storage.yandexcloud.net/rt-pepper/cla-porfolio/suvenir/suvenir_1_1.png',
        'https://storage.yandexcloud.net/rt-pepper/cla-porfolio/suvenir/suvenir_2.png',
        'https://storage.yandexcloud.net/rt-pepper/cla-porfolio/suvenir/suvenir_1_2.png',
        'https://storage.yandexcloud.net/rt-pepper/cla-porfolio/suvenir/suvenir_3.png',
        'https://storage.yandexcloud.net/rt-pepper/cla-porfolio/suvenir/suvenir_1_3.png',
        'https://storage.yandexcloud.net/rt-pepper/cla-porfolio/suvenir/suvenir_4.png',
        'https://storage.yandexcloud.net/rt-pepper/cla-porfolio/suvenir/suvenir_1_4.png',
        'https://storage.yandexcloud.net/rt-pepper/cla-porfolio/suvenir/suvenir_5.png',
        'https://storage.yandexcloud.net/rt-pepper/cla-porfolio/suvenir/suvenir_1_5.png',
        'https://storage.yandexcloud.net/rt-pepper/cla-porfolio/suvenir/suvenir_6.png',
        'https://storage.yandexcloud.net/rt-pepper/cla-porfolio/suvenir/suvenir_7.png',
        'https://storage.yandexcloud.net/rt-pepper/cla-porfolio/suvenir/suvenir_8.png',
      ],
    },
  ],
  apps: [
    {
      id: 15,
      name: 'Bank App',
      link: 'bankapp',
      description:
        'Приложение для учета расходов: интуитивный интерфейс, возможность управления бюджетом, аналитика по категориям, напоминания о платежах.',
      preview: 'https://storage.yandexcloud.net/rt-pepper/cla-porfolio/applications/modil_0.png',
      images: [
        'https://storage.yandexcloud.net/rt-pepper/cla-porfolio/applications/modil_0.png',
        'https://storage.yandexcloud.net/rt-pepper/cla-porfolio/applications/modil_0_1.png',
        'https://storage.yandexcloud.net/rt-pepper/cla-porfolio/applications/modil_1.png',
        'https://storage.yandexcloud.net/rt-pepper/cla-porfolio/applications/modil_2.png',
        'https://storage.yandexcloud.net/rt-pepper/cla-porfolio/applications/modil_3.png',
        'https://storage.yandexcloud.net/rt-pepper/cla-porfolio/applications/modil_4.png',
        'https://storage.yandexcloud.net/rt-pepper/cla-porfolio/applications/modil_5.png',
      ],
    },
  ],
  bunners: [
    {
      id: 21,
      name: 'Edu',
      link: 'edu',
      description:
        'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Cum quibusdam numquam recusandae corrupti enim veritatis, vel ab adipisci rerum facere.',
      preview: 'https://storage.yandexcloud.net/rt-pepper/cla-porfolio/banner/edu/Edu_0.png',
      images: ['https://storage.yandexcloud.net/rt-pepper/cla-porfolio/banner/edu/Edu_0.png'],
    },
    {
      id: 22,
      name: 'Flowers',
      link: 'flowers',
      description:
        'Элегантные букеты и уникальные композиции: цветы для особых моментов вашей жизни.',
      preview:
        'https://storage.yandexcloud.net/rt-pepper/cla-porfolio/banner/flowers/flowers_0.png',
      images: [
        'https://storage.yandexcloud.net/rt-pepper/cla-porfolio/banner/flowers/flowers_0.png',
        'https://storage.yandexcloud.net/rt-pepper/cla-porfolio/banner/flowers/flowers_0_0.png',
        'https://storage.yandexcloud.net/rt-pepper/cla-porfolio/banner/flowers/flowers_1.png',
        'https://storage.yandexcloud.net/rt-pepper/cla-porfolio/banner/flowers/flowers_1_1.png',
      ],
    },
  ],
};
